export ADOS_URL=http://10.200.1.239:8080/tfs
export ADOS_USERNAME=Administrator
export ADOS_COLLECTION=DefaultCollection
export ADOS_PROJECT_NAME=ahorodchuk_test
export ADOS_PASSWORD=Mbimp,vm
export ADOS_TOKEN=byvw46n7i2hrp37hscvmbefbvchs4pc6dhgqdn5vyj7fm3c6gohq
export ADOS_API_VERSION=3.0
export ADOS_AUTH_NTLM=true
export BUILD_DEFINITION_NAME="Sample Gradle Build-dryRun"