
// Was generated by REST Plugin Wizard
def procName = 'GetWorkItems'
def stepName = 'get work items'
procedure procName, description: 'Retrieves a list of the work items', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::AzureDevOps::Plugin;
EC::AzureDevOps::Plugin->new->step_get_work_items();
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
