
// Was generated by REST Plugin Wizard
def procName = 'Get a Work Item'
def stepName = 'get a work item'
procedure procName, description: 'Returns the content of the work item', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('get a work item');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
