
// Was generated by REST Plugin Wizard
def procName = 'Get a Build'
def stepName = 'get a build'
procedure procName, description: 'Gets a specified build info', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('get a build');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
