
// Was generated by REST Plugin Wizard
def procName = 'TriggerBuild'
def stepName = 'trigger a build'
procedure procName, description: 'Queues a new build', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('trigger a build');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
