
// Was generated by REST Plugin Wizard
def procName = 'TriggerBuild'
def stepName = 'trigger a build'
procedure procName, description: 'Queues a new build', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::AzureDevOps::Plugin;
EC::AzureDevOps::Plugin->new->step_trigger_build;
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
