
// Was generated by REST Plugin Wizard
def procName = 'GetBuild'
def stepName = 'get a build'
procedure procName, description: 'Gets a specified build info.', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::AzureDevOps::Plugin;
EC::AzureDevOps::Plugin->new->step_get_build();
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
