
// Was generated by REST Plugin Wizard
def procName = 'CreateWorkItems'
def stepName = 'create work items'
procedure procName, description: 'Creates new work items', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::AzureDevOps::Plugin;
EC::AzureDevOps::Plugin->new->step_create_work_items();
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
