
// Was generated by REST Plugin Wizard
def procName = 'Update a Work Item'
def stepName = 'update a work item'
procedure procName, description: 'Update a work item fields', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('update a work item');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
