
// Was generated by REST Plugin Wizard
def procName = 'Delete a Work Item'
def stepName = 'delete a work item'
procedure procName, description: 'Deletes the specified work item', {

    step stepName,
        command: """
\$[/myProject/scripts/preamble]
use EC::RESTPlugin;
EC::RESTPlugin->new->run_step('delete a work item');
""",
        errorHandling: 'failProcedure',
        exclusiveMode: 'none',
        releaseMode: 'none',
        shell: 'ec-perl',
        timeLimitUnits: 'minutes'

}
