export ADOS_URL=https://dev.azure.com
export ADOS_USERNAME=pluginsdev
export ADOS_COLLECTION=pluginsdev
export ADOS_PROJECT_NAME=ahorodchuk_test
export ADOS_TOKEN=cmq2qvktsyg5eculgleevfsqjznfhfmatmkgtkxhenioi7cuwvxa
export ADOS_API_VERSION=4.1
export BUILD_DEFINITION_NAME=Sample Gradle Build-dryRun